const ADD_FITNESS_ACTIVITY = 'rails-react-app/ADD_FITNESS_ACTIVITY';
const GET_FITNESS_ACTIVITIES = 'rails-react-app/GET_FITNESS_ACTIVITIES';
const DELETE_FITNESS_ACTIVITY = 'rails-react-app/DELETE_FITNESS_ACTIVITY';
const GET_FITNESS_ACTIVITY = 'rails-react-app/GET_FITNESS_ACTIVITY';

const ADD_RESERVATION = 'rails-react-app/ADD_RESERVATION';

const GET_RESERVATIONS = 'rails-react-app/GET_RESERVATIONS';

const GET_AVAILABLE_DATES = 'rails-react-app/GET_AVAILABLE_DATES';

const GET_JWT_TOKEN = 'rails-react-app/GET_JWT_TOKEN';

export {
  ADD_FITNESS_ACTIVITY,
  GET_FITNESS_ACTIVITIES,
  DELETE_FITNESS_ACTIVITY,
  GET_FITNESS_ACTIVITY,
  ADD_RESERVATION,
  GET_RESERVATIONS,
  GET_AVAILABLE_DATES,
  GET_JWT_TOKEN,
};
