const GET_FITNESS_ACTIVITIES = 'rails-react-app/GET_FITNESS_ACTIVITIES';
const DELETE_FITNESS_ACTIVITY = 'rails-react-app/DELETE_FITNESS_ACTIVITY';

export { GET_FITNESS_ACTIVITIES, DELETE_FITNESS_ACTIVITY };
